ALTER TABLE GROUP_MEMBER ADD COLUMN MANAGER BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS `SSH_KEY` (
  `SSH_KEY_ID` INT AUTO_INCREMENT PRIMARY KEY,
  `USER_NAME` VARCHAR(100) NOT NULL,
  `TITLE` VARCHAR(100) NOT NULL,
  `PUBLIC_KEY` TEXT NOT NULL,
  CONSTRAINT `IDX_SSH_KEY_0` UNIQUE (`USER_NAME`, `SSH_KEY_ID`),
  CONSTRAINT `IDX_SSH_KEY_FK0` FOREIGN KEY (`USER_NAME`) REFERENCES `ACCOUNT` (`USER_NAME`)
);
