CREATE TABLE IF NOT EXISTS `ACTIVITY`(
    `ACTIVITY_ID` INT AUTO_INCREMENT PRIMARY KEY,
	`USER_NAME` VARCHAR(100) NOT NULL,
	`REPOSITORY_NAME` VARCHAR(100) NOT NULL,
	`ACTIVITY_USER_NAME` VARCHAR(100) NOT NULL,
	`ACTIVITY_TYPE` VARCHAR(100) NOT NULL,
	`MESSAGE` TEXT NOT NULL,
	`ADDITIONAL_INFO` TEXT,
	`ACTIVITY_DATE` TIMESTAMP NOT NULL,
	CONSTRAINT `IDX_ACTIVITY_FK0` FOREIGN KEY (`USER_NAME`, `REPOSITORY_NAME`) REFERENCES `REPOSITORY` (`USER_NAME`, `REPOSITORY_NAME`),
	CONSTRAINT `IDX_ACTIVITY_FK1` FOREIGN KEY (`ACTIVITY_USER_NAME`) REFERENCES `ACCOUNT` (`USER_NAME`)
);

CREATE TABLE IF NOT EXISTS `COMMIT_LOG` (
	`USER_NAME` VARCHAR(100) NOT NULL,
	`REPOSITORY_NAME` VARCHAR(100) NOT NULL,
	`COMMIT_ID` VARCHAR(40) NOT NULL,
	PRIMARY KEY(`USER_NAME`, `REPOSITORY_NAME`, `COMMIT_ID`),
	CONSTRAINT `IDX_COMMIT_LOG_FK0` FOREIGN KEY (`USER_NAME`, `REPOSITORY_NAME`) REFERENCES `REPOSITORY` (`USER_NAME`, `REPOSITORY_NAME`)
);
