CREATE TABLE `GROUP_MEMBER`(
    `GROUP_NAME` VARCHAR(100) NOT NULL,
    `USER_NAME`  VARCHAR(100) NOT NULL,
    PRIMARY KEY (`GROUP_NAME`, `USER_NAME`),
    CONSTRAINT `IDX_GROUP_MEMBER_FK0` FOREIGN KEY (`GROUP_NAME`) REFERENCES `ACCOUNT` (`USER_NAME`),
    CONSTRAINT `IDX_GROUP_MEMBER_FK1` FOREIGN KEY (`USER_NAME`) REFERENCES `ACCOUNT` (`USER_NAME`)
);

ALTER TABLE `ACCOUNT` ADD COLUMN `GROUP_ACCOUNT` BOOLEAN NOT NULL DEFAULT FALSE;

CREATE OR REPLACE VIEW `ISSUE_OUTLINE_VIEW` AS
 SELECT
   A.USER_NAME,
   A.REPOSITORY_NAME,
   A.ISSUE_ID,
   COUNT(*) AS COMMENT_COUNT
 FROM ISSUE A LEFT JOIN ISSUE_COMMENT B
   ON (A.USER_NAME = B.USER_NAME AND A.REPOSITORY_NAME = B.REPOSITORY_NAME AND A.ISSUE_ID = B.ISSUE_ID) AND B.`ACTION` IN ('comment', 'close_comment', 'reopen_comment')
   GROUP BY USER_NAME, REPOSITORY_NAME, ISSUE_ID;
