CREATE TABLE `WEB_HOOK` (
    `HOOK_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `USER_NAME` VARCHAR(100) NOT NULL,
	`REPOSITORY_NAME` VARCHAR(100) NOT NULL,
	`URL` VARCHAR(200) NOT NULL,
    CONSTRAINT `IDX_WEB_HOOK_FK0` FOREIGN KEY (`USER_NAME`, `REPOSITORY_NAME`) REFERENCES `REPOSITORY` (`USER_NAME`, `REPOSITORY_NAME`)
);

